Fe layout WIP
Assisted-Math-Learning/aml-portal pull request #12
Opened 2024-10-09 15:33 UTC by arshDevslane

2024-10-17 07:09 UTC, HarishGangula requested changes

2024-10-17 07:09 UTC, HarishGangula commented on src/services/api-services/BaseApiService.ts
> +      ts: '2024-09-20T17:43:49+05:30',
Don't hard code this value

2024-10-17 07:09 UTC, HarishGangula commented on src/services/api-services/BaseApiService.ts
> +        msgid: 'd297e367-7b72-45c1-883c-18005a7ea888',
This should dynamic uuid

2024-10-18 06:20 UTC, arshDevslane commented on src/services/api-services/BaseApiService.ts
> +      ts: '2024-09-20T17:43:49+05:30',
Yes for the moment i hardcoded it, it's been fixed now 👍

2024-10-18 06:20 UTC, arshDevslane commented on src/services/api-services/BaseApiService.ts
> +        msgid: 'd297e367-7b72-45c1-883c-18005a7ea888',
this too has been fixed

2024-10-21 04:51 UTC, HarishGangula approved these changes

2024-10-21 04:52 UTC, merged