Collapsible keyboard component
Assisted-Math-Learning/aml-portal pull request #6
Opened 2024-09-04 08:02 UTC by karan-devslane

2024-09-05 05:37 UTC, karan-devslane commented
Collapsed:
![image](https://github.com/user-attachments/assets/8e172110-4b0a-482b-9fbd-15c5d1021535)

Expanded:
![image](https://github.com/user-attachments/assets/026c3a48-3fc2-4c9d-9e95-5d66bf148f59)

2024-09-06 05:06 UTC, HarishGangula requested changes

2024-09-06 05:06 UTC, HarishGangula commented on src/shared-resources/icons/ArrowRight.tsx
> +import React from 'react';
This is not required you can use https://mui.com/material-ui/material-icons/?query=play&theme=Rounded&selected=PlayArrowRounded

2024-09-06 05:26 UTC, HarishGangula approved these changes

2024-09-06 05:26 UTC, merged